apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job
  namespace: dev
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: failed-task
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting task..."
              echo "Something went wrong!"
              exit 1