events {}

http {

    server {

        listen 80;

        location / {

            default_type text/html;

            return 200 '
            <html>
                <head>
                    <title>Kubernetes Day 6</title>
                </head>

                <body>

                    <h1>Kubernetes Networking Project</h1>

                    <p>Nginx frontend is working.</p>

                    <p>
                        Call the backend:
                        <a href="/api">
                            /api
                        </a>
                    </p>

                    <p>
                        Health:
                        <a href="/health">
                            /health
                        </a>
                    </p>

                </body>
            </html>
            ';
        }


        location /api {

            proxy_pass http://backend-service:5000/api;

        }


        location /health {

            proxy_pass http://backend-service:5000/health;

        }

    }

}
