apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: dev

spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

        - name: backend

          image: k8s-backend:v1

          ports:
            - containerPort: 5000