apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment
  namespace: dev

spec:
  replicas: 3

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
        - name: flask
          image: flask-k8s:v1

          ports:
            - containerPort: 5000