events {}

http {

    server {

        listen 80;

        location / {

            default_type text/html;

            return 200 '
            <html>
                <head>
                    <title>Kubernetes Day 3</title>
                </head>

                <body>

                    <h1>🚀 Kubernetes Multi-Service Application</h1>

                    <h2>Nginx Frontend</h2>

                    <p>Frontend is running successfully.</p>

                    <p>
                        Backend:
                        <a href="/api">
                            Flask API
                        </a>
                    </p>

                </body>
            </html>
            ';
        }

        location /api {

            proxy_pass http://flask-service:5000/api;

        }

    }

}

