apiVersion: v1
kind: Service

metadata:
  name: sidecar-service
  namespace: dev

spec:

  type: NodePort

  selector:
    app: sidecar-app

  ports:

    - port: 5000
      targetPort: 5000
      nodePort: 30087