apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: flask-data-pvc
  namespace: dev

spec:
  storageClassName: local-path

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi